# Recompile core for our custom target
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rust_os.json"

# So the initialization happens at runtime
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

# Lock until mutex is free again
[dependencies]
spin = "0.5.2"

# For targets with "os" field set to "none", specify the bootimage command
# to be run after build success
[target.'cfg(target_os = "none")']
runner = "bootimage runner"