# Recompile core for our custom target
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rust_os.json"

# For targets with "os" field set to "none", specify the bootimage command
# to be run after build success
[target.'cfg(target_os = "none")']
runner = "bootimage runner"